Remove unused imports
Found by flake8:
run-tests.py:3:1: F401 'imp' imported but unused
setup.py:2:1: F401 'stat' imported but unused
datasource/DataHub.py:51:5: F401 'json' imported but unused
datasource/bases/RDBSHub.py:45:1: F811 redefinition of unused 'sys' from line 41
datasource/hubs/MySQL.py:7:1: F401 '_mysql' imported but unused