Make DataHubError derive from BaseException for Python 3 compatibility
Since otherwise under Python 3 this results in:
TypeError: exceptions must derive from BaseException